### ISSUE TITLE
Feature: User can view home Screen

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/gym-buddie#5]
## ⚙️ Feature
User can view the home screen layout

## 📐 Functionality

Provide access for users to choose which feature they want to use.

## 🖼️ Wireframes

![Capture](https://user-images.githubusercontent.com/70422100/132082904-624f92c6-340d-4360-b669-dd9edc5cb904.PNG)

## ✅ Task 

- [x] create new react app with needed packages
- [x] install material uiv5
- [x] test to see if it is working by creating a hello world
- [x] remove hello world
- [ ] following the mui documentation create a grid that takes 6, 2, 2 
- [ ] add the name of the app along with the icon
- [ ] add the buttoin for the barcode along witht he item
- [ ] add the hamburger menu.
- [ ] create the calender component that will take the full grid scale of 12
- [ ] create the buttons on dividing the grid by 2 (scale = 6)
- [ ] add needed styling to make the button the correct size.
- [ ] add icons to the layout
- [ ] add color to match figma

### 🧑‍⚕️ Clean Up

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
